package com.openclassrooms.realestatemanager.repositories

import androidx.lifecycle.LiveData
import com.openclassrooms.realestatemanager.database.dao.CompositionPropertyAndLocationOfInterestDao
import com.openclassrooms.realestatemanager.models.CompositionPropertyAndLocationOfInterest

class CompositionPropertyAndLocationOfInterestDataRepository(private val compositionPropertyAndLocationOfInterestDao: CompositionPropertyAndLocationOfInterestDao) {

    fun getLocationsOfInterest(propertyId: Int): LiveData<List<CompositionPropertyAndLocationOfInterest>> = compositionPropertyAndLocationOfInterestDao.getLocationsOfInterest(propertyId)

    fun insertLocationOfInterest(compositionPropertyAndLocationOfInterest: CompositionPropertyAndLocationOfInterest): Long = compositionPropertyAndLocationOfInterestDao.insertLocationOfInterest(compositionPropertyAndLocationOfInterest)

    fun updateCompositionPropertyAndLocationOfInterest(compositionPropertyAndLocationOfInterest: CompositionPropertyAndLocationOfInterest): Int = compositionPropertyAndLocationOfInterestDao.updateCompositionPropertyAndLocationOfInterest(compositionPropertyAndLocationOfInterest)

    fun deleteLocationOfInterest(propertyId: Int, locationOfInterestId: Int) = compositionPropertyAndLocationOfInterestDao.deleteLocationOfInterest(propertyId, locationOfInterestId)

}